"""One-off: port elnovian's style.css + effect CSS into LCT (resources/css/site.css).

- rem -> px (elnovian ran html at 62.5%, LCT keeps the 16px root)
- :root palette remapped to LCT (see TOKENS)
- every rule scoped under .el-site, inside @layer components so Tailwind
  utilities still win, as they did in elnovian's load order
"""
import re, sys, pathlib

SRC = pathlib.Path(sys.argv[1])
OUT = pathlib.Path('resources/css/site.css')

TOKENS = """:root {
    /* elnovian token names, LCT values: foam black, signal red, brushed steel */
    --sb-green: #b80f14;
    --green-accent: #d7141a;
    --house-green: #1b1b1d;
    --green-uplift: #2d2d31;
    --green-light: #ececea;
    --gold: #a8abaf;
    --gold-light: #c7c9cc;
    --gold-lightest: #f6f6f4;
    --cream: #f4f4f2;
    --ceramic: #ececea;
    --white: #ffffff;
    --neutral-cool: #f9f9f9;
    --text-black: rgba(17, 17, 19, 0.9);
    --text-black-soft: rgba(17, 17, 19, 0.64);
    --text-white: #ffffff;
    --text-white-soft: rgba(255, 255, 255, 0.74);
    --input-border: #c7c9cc;
    --hairline: #e2e2e0;
    --red: #d7141a;
    --radius-card: 8px;
    --radius-card-lg: 14px;
    --radius-pill: 6px;
    --shadow-card: 0 0 0.5px rgba(0, 0, 0, 0.16), 0 1px 2px rgba(0, 0, 0, 0.22);
    --shadow-nav: 0 1px 3px rgba(0, 0, 0, 0.35);
    --shadow-frap-base: 0 0 6px rgba(0, 0, 0, 0.3);
    --shadow-frap-ambient: 0 8px 12px rgba(0, 0, 0, 0.2);
    --shadow-frap-ambient-active: 0 8px 12px rgba(0, 0, 0, 0);
    --space-1: 4px;
    --space-2: 8px;
    --space-3: 16px;
    --space-4: 24px;
    --space-5: 32px;
    --space-6: 40px;
    --space-7: 48px;
    --space-8: 56px;
    --space-9: 64px;
    --font-primary: 'Poppins', ui-sans-serif, system-ui, sans-serif;
    --font-display: 'Satoshi', 'Poppins', ui-sans-serif, sans-serif;
}
"""


def rem_to_px(css):
    return re.sub(r'(?<![\w.-])(-?\d*\.?\d+)rem\b', lambda m: f"{float(m.group(1)) * 10:g}px", css)


def strip_comments(css):
    return re.sub(r'/\*.*?\*/', '', css, flags=re.S)


def blocks(css):
    """Yield (prelude, body) for each top-level block."""
    i, n = 0, len(css)
    while i < n:
        j = css.find('{', i)
        if j < 0:
            break
        prelude = css[i:j].strip()
        depth, k = 1, j + 1
        while depth and k < n:
            depth += {'{': 1, '}': -1}.get(css[k], 0)
            k += 1
        yield prelude, css[j + 1:k - 1]
        i = k


def scope(selectors, prefix='.el-site'):
    out = []
    for s in selectors.split(','):
        s = s.strip()
        if not s:
            continue
        out.append(f"{prefix} {s}" if prefix else s)
    return ',\n'.join(out)


def port(css, skip=('*', 'html', 'body', ':root'), prefix='.el-site'):
    css = rem_to_px(strip_comments(css))
    keyframes, rules = [], []
    for prelude, body in blocks(css):
        if prelude.startswith('@keyframes'):
            keyframes.append(f"{prelude} {{{body}}}")
        elif prelude.startswith('@media') or prelude.startswith('@supports'):
            inner = '\n'.join(f"    {scope(p, prefix)} {{{b}}}" for p, b in blocks(body))
            rules.append(f"{prelude} {{\n{inner}\n}}")
        elif prelude.startswith('@layer'):
            rules.append(port(body, skip, prefix)[0])
        elif prelude in skip:
            continue
        else:
            rules.append(f"{scope(prelude, prefix)} {{{body}}}")
    return '\n'.join(rules), '\n'.join(keyframes)


style = SRC.joinpath('public/css/style.css').read_text(encoding='utf-8')
app = SRC.joinpath('resources/css/app.css').read_text(encoding='utf-8')
app = app[app.index('@tailwind utilities;') + len('@tailwind utilities;'):]
# the rates-page rules are elnovian-only
app = re.sub(r'\.rates-page[^{]*\{[^}]*\}', '', app)

r1, k1 = port(style)
# The effect CSS (layered button, marquee, ...) is class-based and also used
# by the shop, which sits outside .el-site: leave it unscoped.
r2, k2 = port(app, prefix='')

OUT.write_text(
    "/* Generated by scripts/port_elnovian_css.py from elnovian-react-laravel. */\n"
    + TOKENS
    + "\n@layer components {\n" + r1 + "\n" + r2 + "\n}\n\n" + k1 + "\n" + k2 + "\n",
    encoding='utf-8',
)
print(OUT, OUT.stat().st_size)
